In [4]:
import numpy as np

In [6]:
Q = np.array([[1,2],[3,4]])

In [7]:
Q

array([[1, 2],
       [3, 4]])

In [15]:
Q.T

array([[1, 3],
       [2, 4]])

In [12]:
np.linalg.norm(Q,axis=1)

array([2.23606798, 5.        ])

In [16]:
(Q.T/np.linalg.norm(Q,axis=1)).T

array([[0.4472136 , 0.89442719],
       [0.6       , 0.8       ]])